### ISSUE TITLE
Remove ploomber-extension from required dependencies

### ISSUE THREAD

**Issue by hlapp** [ploomber/jupysql#1025]
The "Share notebook" button created (in my understanding) by the ploomber-extension dependency is not acceptable in my environment (educational institution). (It uses a non-vetted platform and is thus by definition insecure.)

It seems this dependency was added months ago, for the sole reason to have this button. It appears none of the jupysql functionality is otherwise dependent on or affected by this extension, as arguably it should be if it wants to be a successor to ipython-sql.

Hence, how can this be disabled _by default_, and/or be excluded from the mandatory requirements.

**Comment by edublancas** [comment]
Hi,

we're deprecating the "share notebook" feature so we'll remove the ploomber-extension soon.


for now, you can write an installation script that uninstalls it:

```
pip install jupysql
pip uninstall ploomber-extension
```

if that doesn't work, we'd appreciate your help with a PR: https://github.com/ploomber/jupysql-plugin/

so we remove ploomber-extension

**Comment by hlapp** [comment]
I added a PR. ploomber-extension is actually not used in [jupysql-plugin/](https://github.com/ploomber/jupysql-plugin/), AFAICT.

**Comment by edublancas** [comment]
Hi @hlapp, you [mentioned](https://github.com/ploomber/jupysql/issues/1027) you're being forced to move to ipython-sql because of our telemetry and a a few other things.

for full transparency: we're a small startup putting our own resources to fund JupySQL's development. it seems like our business model does not fit your requirements, so I'll have to politely decline working with you. as we cannot accommodate your requests

**Comment by hlapp** [comment]
Is there a reason you refused this (#1026) PR? You at first expressly asked for it, and I obliged your request and submitted it.

**Comment by hlapp** [comment]
I think this was addressed through #1026 and #1028. Thanks @edublancas and @neelasha23 👍
