### ISSUE TITLE
update JSON tutorial

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#122]
DuckDB currently expects JSON data to contain one object per line; however, this will be fixed so we must update it once the new version is out: https://github.com/ploomber/jupysql/pull/119#discussion_r1100018089

**Comment by edublancas** [comment]
https://duckdb.org/2023/02/13/announcing-duckdb-070.html

**Comment by gtduncan** [comment]
I’m having some issues here— everything seems to work fine with the new DuckDB `.json` support when it’s first loaded: 

<img width="657" alt="Screen Shot 2023-02-22 at 10 50 15 AM" src="https://user-images.githubusercontent.com/106283285/220743662-a5f6af16-eacf-4d17-a431-1d1214fba039.png">

but I can no longer use the `'$.name'` format to select every object from the json array. Seen here, I can easily access a singular object with `'$[0].name'` for example:

<img width="661" alt="Screen Shot 2023-02-22 at 10 37 55 AM" src="https://user-images.githubusercontent.com/106283285/220743878-6eb1566b-ac35-478d-ae48-9c7d947f6b15.png">

 but it returns none when I attempt to select them all with `'$.name'`:

<img width="669" alt="Screen Shot 2023-02-22 at 10 48 50 AM" src="https://user-images.githubusercontent.com/106283285/220743983-368532ed-ce22-4cb7-8afe-b6edb69afbff.png">

I also tried using duckDB’s new `read_json_auto` method that is supposed to return a json file in a tabular format instead of the original `read_json_objects`, but then it throws an error saying that the json is malformed. Any ideas? (ignore getting `$.likes.pizza` as `likes_tacos`, just fixed that). I was considering trying to use some sort of SQL iterator but that seemed like it may be too much.

**Comment by edublancas** [comment]
hey @Mause, can you help us here?

we want to update our [tutorial](https://jupysql.ploomber.io/en/latest/howto/json.html) with the new JSON features in DuckDB 0.7.

Given a JSON file with a list of objects `[{...}, {...}, ...]`, my assumption is that DuckDB can only read each object as a "row" if it's in JSON lines format (e.g., this shows 4 rows in the output):

<img width="807" alt="image" src="https://user-images.githubusercontent.com/989250/220754187-e5c2b00d-4edb-4133-8f34-af4402b4edb7.png">

seems like we cannot process one object at a time when the same data is in regular JSON format (a single row in the output):

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/989250/220754386-c554dad0-f130-4e67-97fe-2c237b90c084.png">

**Comment by Mause** [comment]
@lnkuiper can probably help more here, but you can do something like this?

```sql
SELECT row(name, age, likes)::json
FROM read_ndjson_auto('people.jsonl')
```
```
┌─────────────────────────────────────────────────────────────────────┐
│             CAST(main.row("name", age, likes) AS json)              │
│                                json                                 │
├─────────────────────────────────────────────────────────────────────┤
│ {'name': John, 'age': 25, 'likes': {'pizza': true, 'tacos': true}}  │
│ {'name': Jake, 'age': 20, 'likes': {'pizza': false, 'tacos': true}} │
│ {'name': Kelly, 'age': 21, 'likes': {'pizza': true, 'tacos': true}} │
│ {'name': Sam, 'age': 22, 'likes': {'pizza': false, 'tacos': true}}  │
└─────────────────────────────────────────────────────────────────────┘
```

**Comment by lnkuiper** [comment]
Hi,

I initially implemented only NDJSON support, but we now also support reading a JSON array of objects. This will be in the upcoming 0.7.1 bugfix release.

However, for now you can do something like this:
```sql
select p.* from (select unnest(json) p from 'people.jsonl');
```
This unnests the `LIST`, then explodes the struct using `*`.

**Comment by edublancas** [comment]
thanks a lot @Mause and @lnkuiper for your feedback!

**Comment by edublancas** [comment]
@gtduncan let's resume this work once 0.7.1 is out

**Comment by Mause** [comment]
v0.7.1 is now out ;)

**Comment by edublancas** [comment]
hey @gtduncan - let's resume this work.

let's re-write the example so we use `read_json_auto` with a .json file, but also mention that .jsonl is supported. please add a note telling users that they should use duckdb>=0.7.1


sample notebook: [duckdb-json.ipynb.zip](https://github.com/ploomber/jupysql/files/10861316/duckdb-json.ipynb.zip)
