### ISSUE TITLE
Feature request: support for SqlMagic.autopolars

### ISSUE THREAD

**Issue by jorisroovers** [ploomber/jupysql#138]
Thanks for creating `jupysql`, I've been playing with it for a few days and it's awesome!

Since I've been experimenting with [polars](https://www.pola.rs/) at the same time, I thought it would be useful for jupysql to support `SqlMagic.autopolars`, automatically converting results to polars Dataframes, similar to `SqlMagic.autopandas`.

I've had a quick look at the source code and I *think* this is a relatively small change, I'd be happy to make an attempt if this is something you'd accept (I'd add docs and tests too).

One thing wrt implementation I'm not sure is easy to do is the fact that ideally `SqlMagic.autopolars` and `SqlMagic.autopandas` should be mutually exclusive, i.e. an error should show if you set both to true. I haven't dug deeply into the code though, perhaps that's not too hard either.

**Comment by edublancas** [comment]
hey @jorisroovers, thanks for your feedback!

yeah, this sounds like a good addition, so feel free to open a PR. A few pointers:

## converting to polars

this is how I  managed to convert to polars:

```sql
%%sql results <<
SELECT species, COUNT(*) AS count
FROM penguins.csv
GROUP BY species
ORDER BY count DESC
```

```python
import polars as pl

pl.DataFrame((tuple(row) for row in results), schema=results.keys)
```

Note that this is a bit inefficient since we need to convert every row into a tuple (polar breaks if we don't); I think this is ok for a first implementation.

## adding `.to_polars()`

The conversion should happen in the ResultSet object (run.py file), check the `DataFrame()` (pandas conversion) so you get an idea. polars should be an optional dependency so include the import inside the function.

Then, to connect it with the new autopolars logic, we need to modify the run function (also in the run.py file)


## mutually exclusive option

I think when calling `autopandas`, `autopolars` should be automatically turned off and vice-versa. we should also display a message letting the user know (i.e., something like "turned autopandas off since autopolars was turned on")

**Comment by edublancas** [comment]
in the meantime, I documented how to convert to polars manually: we can remove this once the PR is merged: https://jupysql.ploomber.io/en/latest/howto.html#convert-to-polars-dataframe

**Comment by jorisroovers** [comment]
Excellent, I will make attempt this week!

**Comment by tonykploomber** [comment]
Thanks for the feedback, @jorisroovers 

You can also see our [contribute guide](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md) to check more info when you are making the changes!
