### ISSUE TITLE
updating integrations with new features

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#246]
When https://github.com/ploomber/jupysql/pull/164 is merged, we'll be able to run many of the features in other databases, so we should update the integrations section in our tutorials so they showcase them. Just so you know, some of them might not work so please report any incompatibilities.

for the following integrations: MySQL, Microsoft SQL server, mariadb, postgres

we need to ensure that the tutorials show how to use 

ctes https://jupysql.ploomber.io/en/latest/compose.html
listing columns and tables https://jupysql.ploomber.io/en/latest/user-guide/tables-columns.html
and plotting https://jupysql.ploomber.io/en/latest/plot.html

**Comment by tonykploomber** [comment]
Current MSSQL fail:
histogram, boxplot

**Comment by tonykploomber** [comment]
Acceptance Criteria:

- Tutorials have been updated to include the features of the other databases.
- The updated tutorials showcase how to use CTEs, list columns and tables, and plot data for MySQL, Microsoft SQL Server, MariaDB, and Postgres.
- The tutorials have been tested to ensure that the features work as expected.
- Any incompatibilities with the features have been reported and addressed.

**Comment by tonykploomber** [comment]
@edublancas 
I checked our integration doc for those databases: MySQL, Microsoft SQL server, mariadb, postgres

MySQL:
- CTE ✅
- Plotting ✅ (without boxplot)
- Listing columns and tables ✅

Microsoft SQL server:
- CTE ✅
- Plotting  ❌ (since it's not supported)
- Listing columns and tables ✅

MariaDB:
- CTE ✅
- Plotting ✅ (without boxplot)
- Listing columns and tables ✅

Postgres:
- CTE ✅
- Plotting ✅ (without boxplot)
- Listing columns and tables ✅
 
@edublancas 
I think we've covered those primary functions in those docs, do you think is anything we could do better on this issue?

Or probably we can close the issue

**Comment by edublancas** [comment]
alright, yeah. that's good. we're covering the basics
