### ISSUE TITLE
Add support for MSSQL in sqlglot

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/jupysql#297]
Currently, when using `--with` and `--save` args with `%sql` using MSSQL engine, it gives error. It is mainly due to wrong parsing by sqlglot as it doesn't support MSSQL
#164 #296

**Comment by edublancas** [comment]
the only reason we're using sqlglot for the --with feature is to allow us to build the CTE since some dbs need backticks. But we don't really need to parse the user queries (nor we should as it will lead to unexpected problems like this one).

The best solution here is not to use sqlglot to build the CTE, let's do the way we were doing it before (with jinja) and just a conditional that determines whether to use backticks or double quotes based on the dialect

**Comment by edublancas** [comment]
this has been fixed in #307
