### ISSUE TITLE
Add OracleDB to integration tests and documentation

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#329]
To have more robust tests let's add this DB in: [Maybe Oracle](https://github.com/oracle/docker-images/tree/main/OracleDatabase)

**Comment by tonykploomber** [comment]
After some researches seems oracle enterprise version is not easy to integrate with.

I am using this [oracle-xe](https://hub.docker.com/r/gvenzl/oracle-xe) now, will report the progress if any updates

**Comment by tonykploomber** [comment]
Development Note:
To start oracle docker instance on Mac M1/M2 chips
1. We need to use [colima](https://github.com/abiosoft/colima) to simulate x86 machine, install colima on your Mac through homebrew
2. Start `colima start --cpu 4 --memory 4 --disk 10` virtual machine environment (This matters, or your container might fail)
3. To test if oracle container can be run by `docker run -d -p 1521:1521 -e ORACLE_PASSWORD=admin123 -e APP_USER=my_user -e APP_USER_PASSWORD=my_password gvenzl/oracle-xe`

**Comment by tonykploomber** [comment]
It's in progress now.

TODO LIST:
- [ ] Setup the local running command on docker
- [ ] Setup the config testing module in `_testing` 
- [ ] Setup the dynamic docker client fetcher by colima or native docker API (Since Mac M1 users need additional setup)
- [ ] Add to generous integration testing
- [ ] Add to individual integration testing
- [ ] Add colima section in developer doc 
- [ ] Add OracleDB integration doc
