### ISSUE TITLE
mismatch on %sql charindex

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#33]
reproduce and solve this [reported issue](https://github.com/catherinedevlin/ipython-sql/issues/176)

**Comment by edublancas** [comment]
tip: the problem is most likely in the parsing logic. We can test it in `test_command.py`

**Comment by yafimvo** [comment]
Yes, it seems like the root of the problem is with the parsing logic (which happens only when trying to find the index of an empty char - ' ')

It happens [here](https://github.com/ploomber/jupysql/blob/9367c226d0d0aa48e6b2f5fbc32595a99a3246ca/src/sql/parse.py#L96) at `parse_argstring(magic_execute, line)`.

i.e:
Given this line
```
line = "SELECT CHARINDEX(' ', 'AAA BBB CCC')"
```

It parses it to
```
['SELECT', "CHARINDEX('", "', '", 'AAA', 'BBB', "CCC')"]
```

which leads to this line (where the first empty char is before 'AAA')
```
SELECT CHARINDEX(' ', ' AAA BBB CCC')
```

Is it something that we can override? and if so, do we want to do it?


In the meantime, I tried this weird walkaround that so far worked and passed all the current tests.
If the given command is not a cell command and no args were given, so we transform the line into a cell and remove the line.

@edublancas @idomic 
let me know what you think

**Comment by idomic** [comment]
> Can we override it?
I think we can and we should.

> In the meantime, Since the cell is working OK, I tried this weird walkaround that so far worked and passed all the current tests.

Is it possible there's no test cases covering this use case?

> If the given command is not a cell command and no args were given, so we transform the line into a cell and remove the line.

@yafimvo I'm not so clear on this workaround, what's the result of the execution?

**Comment by yafimvo** [comment]
> I think we can and we should.

I'm not sure which function to override. The `parse_argstring` comes from IPython

`from IPython.core.magic_arguments import parse_argstring`

> @yafimvo I'm not so clear on this workaround, what's the result of the execution?
> I think in general we should have the same behavior for `%sql` and `%%sql`, given the later is outputting the right index, we should mimick this behavior imo.

Everything remains the same for the user, `%sql` and `%%sql`. It just executes some line queries as cell queries.

![image](https://user-images.githubusercontent.com/103026689/210269566-4931f2dc-2de2-4fcd-95e7-71f0db19c5ed.png)

**Comment by edublancas** [comment]
I'm confused about the state of this. The original issue reported that the behavior of `%sql` and `%%sql` was different but based on @yafimvo's screenshot looks like they behave the same (?)

**Comment by yafimvo** [comment]
@edublancas the screenshot is after my walkaround.

The root of the problem is bad parsing when using `%sql` with this specific query (trying to find the empty char).

**Comment by edublancas** [comment]
Ok, I understand the problem now. The `parse_argstring` from `IPython.core.magic_arguments` was designed to parse shell-like arguments. Example:

```
{program} {command} arg1 arg2 -a --something value
```

The problem is that users might pass an embedded SQL query:

```
{program} {command} arg1 arg2 -a --something value {some-sql-query-here}
```

And the query might contain spaces, leading to errors in parsing.

This isn't a simple fix since we're essentially using IPython's argparser for something it wasn't designed to do. I'd suggest keeping this in the backlog, since it doesn't seem to be a critical issue.

**Comment by idomic** [comment]
@edublancas Why don't we use this workaround? It aligns the behavior.

**Comment by edublancas** [comment]
Because the workaround involves the user changing their SQL query.

From this:

```
line = "SELECT CHARINDEX(' ', 'AAA BBB CCC')"
```

to this:

```
line = "SELECT CHARINDEX(' ', ' AAA BBB CCC')"
```

and this is information that users don't know (they don't know there is a parser error and they should add this weird extra leading space).

**Comment by yafimvo** [comment]
@edublancas The user changes nothing. He executes the same query with `%sql` but behind the scene, we execute it as `%%sql` (instead of line we execute as cell).

i.e:
```
%%sql
SELECT CHARINDEX(' ', 'AAA BBB')
```

```
%sql SELECT CHARINDEX(' ', 'AAA BBB')
```

both these runs will return 4

**Comment by edublancas** [comment]
I see. but the implementation might be a problem, right? how do we know when we execute `%sql` as `%%sql`?

**Comment by idomic** [comment]
Maybe 1 easy rule is if it contains a space.
Is there functionality that one has over the other? 
I assumed it was just a styling matter.

**Comment by idomic** [comment]
I don't think it's a long term solution but more of a workaround so I see your point, maybe it's better to fix it ground up.

**Comment by edublancas** [comment]
Space isn't enough. A `%sql` command can contain valid spaces for arguments.

**Comment by yafimvo** [comment]
yes, spaces would be enough here. I can push a PR with more tests so you'll see it.

It's not a long-term solution but passed all the current tests. The logic here was if it's `%sql` without arguments (which means just a query to execute) - run it as if it was a cell `%%sql`.

something like this

```python
        if not cell:
            if not _any_arg_given:
                cell = line
                line = ""
```

**Comment by edublancas** [comment]
Ok, let's see the tests and decide

**Comment by idomic** [comment]
Closing this issue given its an edge case and we need more user feedback on it.
