### ISSUE TITLE
Fails to run pytest on the entire project

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#335]
Running `pytest src/tests` raises the following error

```
ImportError while importing test module '/mnt/c/Users/User/Documents/ploomber/environmnets/jupysql-forked/jupysql/src/tests/test_magic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/tests/test_magic.py:15: in <module>
src/tests/test_magic.py:15: in <module>
    from conftest import runsql
```

Executing pytest locally on the entire directory may prevent some unexpected CI failures and save time.

cc: @edublancas

**Comment by edublancas** [comment]
The problem here (which also appears in other repos) is that once our testing suite becomes more complex, we often need to pass arguments to `pytest`. For example, to tun the unit tests for jupysql, we need to execute:

```python
pytest --durations-min=5 --ignore=src/tests/integration
```

This is because we have unit tests and integration tests, and while integration tests can run locally, they need more setup, so it makes sense for them to be optional, since in most cases, contributors only want to run unit tests locally.

I think the best solution here is to standardize how to run unit tests for example add a tasks.py and call them via `invoke unit`; I'll work on this and share any updates.
