### ISSUE TITLE
pending deprecation

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#357]
we have a pending deprecation to apply: https://github.com/ploomber/jupysql/blob/6ae9641bdb080c9c301ed79cfb07297e48320d07/src/sql/store.py#L93

**Comment by edublancas** [comment]
instead of a warning, we should now throw an UsageError exception

**Comment by kewaljani** [comment]
Commenting to assign the issue

**Comment by kewaljani** [comment]
As per my understanding, I think we are able to call the classes individually with the help of 
```
from sql.store import SQLQuery
SQLQuery(sqlstore,"SELECT * FROM KEWAL", ["kewal-"])
``` 
in jupyter notebook
and not just by "--save" command which has a specific flow from magic.py file to store.py file , and I am wondering if it would be better to write exceptions in each class  SQLQuery (line 92 in store.py) instead of only replacing waring in the magic.py file (line 369) (if we want to replace the warning with usage error). What is your opinion on the best practice for this situation?

**Comment by Kaushal-Dhungel** [comment]
Hi, is this issue still open?
