### ISSUE TITLE
Issue on page /api/magic-sql.html

### ISSUE THREAD

**Issue by dominijk** [ploomber/jupysql#421]
Is it still possible to use the syntax

```python
%%sql 
create table db_t_from_some_df 
as select *
from some_df ;
```
or name a dataframe as part of `--persist` ? . If `CREATE TABLE` is supported can that be added to the docs

**Comment by edublancas** [comment]
> Is it still possible to use the syntax

Was this possible before? I'm unsure if this has ever worked since sounds like `some_df` is a dataframe

The way to do it, is via the `--persist` argument, and the table will have the same name as the data frame, you can assign it to a new variable to change the name.

The only case where your snippet will work is if you're using DuckDB, but it won't work with other databases.

**Comment by dominijk** [comment]
Yes, this was on duckdb. Thanks for all the work on jupysql
