### ISSUE TITLE
Obfuscate connection string

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#46]
[This issue](https://github.com/catherinedevlin/ipython-sql/issues/126) discuss printing the connection string as a cell output. We should add some flag to allow the user to avoid this since it's not too secure. In a similar manner [to this](https://github.com/ploomber/jupysql/issues/40), we need to document this flag.

**Comment by edublancas** [comment]
I don't think this should be a flag; we should never display sensitive information, but rather sanitize it.

**Comment by idomic** [comment]
I agree on sanitizing. I proposed a flag since sometimes you'd need to debug, part of it is seeing the connection string and if you clean it by default the user has no alternative.

**Comment by edublancas** [comment]
I did some checking to see what's the state of this. As the original issue explains, the connection string is displayed as:

```
postgres://user:***@194.210.166.48:5432/database
```

The only obfuscated part is the password, but the rest are displayed as is. I guess that the original author intended to display the connection string to explicitly tell the user where the query was executed (since a user might have >1 connection open at the same time)

What I proposed [here](https://github.com/ploomber/jupysql/issues/37#issuecomment-1368125419) for closed connections can also help here. Essentially, we'd allow the user to give each connection a name; we no longer need to print the connection string after any query is run, but rather the connection name.

**Comment by idomic** [comment]
Yeah I think that should work, if there's no prints of the `con_string` besides the output after each command we can close this.

**Comment by edublancas** [comment]
did some quick test and I think this is a good solution.

if a user opens a connection and passes an alias:

```
%sql postgresql://user:password@localhost/db --alias pg
```

Then, we can obfuscate the full string.

Currently:

![image](https://github.com/ploomber/jupysql/assets/989250/10f0923d-2cbc-42c5-a84b-83606bb5968c)


Instead, we can display:

```
*  (pg) postgresql://***:***@***/***
```

**Comment by edublancas** [comment]
I'll tackle this in #432
