### ISSUE TITLE
Add plot types to sqlplot

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/jupysql#483]
Feedback from community:

It'd be great to have the option to do other kinds of plots with the sqlplot magic:
- Line chart
- Scatter plot
- Bar chart

https://jupysql.ploomber.io/en/latest/api/magic-plot.html

**Comment by edublancas** [comment]
bar chart is easy to add, we just need to compute the proportions for each category in the db and then use them to generate the plot.

The other ones are a bit more challenging. The naive approach would be to download all the data and use it to create the line/scatter plot, but this defeats the purpose of using JupySQL, since the idea is to leverage the SQL engine. we might wanna implement something like this: https://datashader.org/

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/jupysql/issues/417
