### ISSUE TITLE
review compatibility guide an integration tests

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#521]
we have an incomplete compatibility [page](https://jupysql.ploomber.io/en/latest/integrations/compatibility.html). When I first created it, I looked at our integration tests and user guides to determine if some feature is compatible or not.

so for each database, and each item in the list vendor we need to see if we have the corresponding integration test (or add one if missing) to determine if a feature is supported or not: if the test passes, we add ✅, if it fails, we put ❌ (and we mark the test with xfail)

we also have corresponding links to each user guide.

these are the database in our integration tests:

- duckdb
- snowflake
- postgres
- mariadb
- MySQL
- msqql
- oracle
- sqlite (this one is missing the entire list)

**Comment by TegveerG** [comment]
My bad, started working on it before including AC: 
1. Currently adding `%sqlplot bar`, `%sqlplot pie`, `ggplot` API examples for DBs that support it -> DuckDB, MariaDB/MySQL, Postgre
2. Testing Snowflake integrations since a good number of them are marked as ❓
3. Test %sqlplot` and `ggplot` API  functions with QuestDB and ClickHouseDB and add their existing functionality to `compatibility.md`
4. The above points (more granular) came up as I probed through the docs, shall update the AC as and when I come across more issues

**Comment by TegveerG** [comment]
I have a question regarding sqlite: is there a dedicated, individual integration guide for it yet or it's with reference to the MindsDB integration?

**Comment by TegveerG** [comment]
**Progress report:**

Changes from current list vendor:
1. `%sqlcmd profile` for Postgre and MariaDB/MySQL was ✅ -> after testing now ❌. Specifically, command runs and outputs for Postgre but output is NaN for all columns except index. Command runs indefinitely for MariaDB/MySQL 
2. `%sql  --interact` for Postgre and MariaDB/MySQL partially ✅. Command works for Basic Data Types and ipywidgets, not for full example. Also, for MariaDB, output/table is displayed twice

Additions to current list vendor:
1. TrinoDB does support `%sqlcmd profile` ✅

**Comment by edublancas** [comment]
great, please open a PR to update the compatibility table

**Comment by TegveerG** [comment]
@edublancas I am struggling a bit writing pytest scripts for testing PostgreSQL integration, I've mainly worked on the integration markdowns and updated functionality there
