### ISSUE TITLE
integrating connection widget

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#632]
- `%sqlcmd connect` should display the widget ([example](https://github.com/ploomber/jupysql-plugin/blob/main/ui-tests/notebooks/connectorWidget.ipynb))
- add a new section to the docs showing how to use it (note that we must ensure [jupysql-plugin](https://github.com/ploomber/jupysql/blob/5b7120f68d6fcf5761f1b657eea877cbbe7d5be7/src/sql/widgets/table_widget/table_widget.py#L158) is installed)

since jupysql-plugin is an optional dependency we need to import it like this:

```python
try:
    import jupysql_plugin
except ModuleNotFoundError:
    jupysql_plugin = None
```

**Comment by edublancas** [comment]
Note: to implement this, you need jupysql-plugin 0.1.5, which I just released

**Comment by edublancas** [comment]
@bbeat2782 we've fixed the problem you encountered when trying to load the connector: https://github.com/ploomber/jupysql-plugin/issues/41 please work on this when you finish your other tasks

**Comment by bbeat2782** [comment]
I will start working on this after I finish the two PRs I opened

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Running `%sqlcmd connect` displays the `ConnectorWidget` and shows connections
2. Ensure when there is no connection (e.g. initial run, kernel restart), the `ConnectorWidget` does not show any connection
3. Add a new section to the docs showing how to use `%sqlcmd connect`

**Comment by edublancas** [comment]
> Ensure when there is no connection (e.g. initial run, kernel restart), the ConnectorWidget does not show any connection

I'm unsure about this one, where is it coming from?


the rest looks fine

**Comment by bbeat2782** [comment]
@edublancas 
Since the `ConnectorWidget` is using a `connections.ini` file to figure out what connections a user currently has, I thought we need to make sure the `connections.ini` file starts empty (when there is no connection) so that the widget displays the correct information.

**Comment by edublancas** [comment]
I think if the connection.ini file isn't empty, then the widget loads connections from it automatically. which makes sense, since I might want to add an existing connection to my .ini file, as opposed to rewriting it.

**Comment by bbeat2782** [comment]
Okay will work on that!

**Comment by edublancas** [comment]
@bbeat2782 I released jupysql-plugin 0.1.9 which fixed the problem you encountered

**Comment by bbeat2782** [comment]
While I was working on this issue, I found this behavior. @edublancas 

As demonstrated in the video, after calling the ConnectorWidget and applying a change (creating a new connection), the change is reflected on the ConnectorWidget display. 

However, if I call another ConnectorWidget in another cell, the change isn't there. The change appears after I modify the widget on that particular cell(e.g. Create new connection).

https://github.com/ploomber/jupysql/assets/43221691/db82d862-d137-4a85-86a2-f9730060fca2

Is this an expected behavior?

**Comment by edublancas** [comment]
@bbeat2782 thanks for reporting this. please open a new issue and post the description and video in https://github.com/ploomber/jupysql-plugin

let's keep with the integration and we can tackle the error you found independently

**Comment by bbeat2782** [comment]
Just opened the issue

**Comment by bbeat2782** [comment]
@edublancas 

Since the section names of connections.ini are aliases of connections, I was working on retrieving an alias of a connection and found that if no `alias` is given from a user, the code saves `_url` as a connection's alias (for `SQLAlchemyConnection` class). This can be checked by running `ConnectionManager._get_connections()`.
<img width="574" alt="Screen Shot 2023-08-01 at 1 59 19 PM" src="https://github.com/ploomber/jupysql/assets/43221691/8ec4f8f0-29e6-4562-8e0f-6323a1949612">

<img width="693" alt="Screen Shot 2023-08-01 at 1 58 16 PM" src="https://github.com/ploomber/jupysql/assets/43221691/a7e40832-4de0-46aa-99b4-3fa73a959c79">

The problem is that including special characters like : or / breaks the ConnectorWidget. I'm able to add the connection but unable to click to connect or delete it. Should this happen? If not, I think I will have to change how the code saves `alias` when it is not given from a user.

https://github.com/ploomber/jupysql/assets/43221691/5543d325-4e03-4730-ac6e-1dbbe17cd0ca

**Comment by edublancas** [comment]
@bbeat2782 thanks for investigating these issues. please report this as well in the jupysql-plugin repository.

this issue is limited to showing the connection widget when executing `%sqlcmd connect`, so no need to worry about these edge cases (it's still good that you're investigating them though!), just ensure the widget shows up and then we'll fix the widget
