### ISSUE TITLE
problem with ggplot histograms

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#702]
there's some error in the ggplot histograms when using the fill option:

![Screenshot 2023-06-30 at 1 38 40 p m](https://github.com/ploomber/jupysql/assets/989250/c511a244-2979-4bd5-8a27-a1a5b2b30940)

from what I understand, fill should display one histogram on top of another with different colors. since these are histograms, they should not have vertical color breaks (beginning from the bottom) where they start with color A, then color B and then they are color A again. since the value in the Y axis is a count. see: https://stackoverflow.com/questions/22216350/overlay-histograms-in-r

![hist](https://github.com/ploomber/jupysql/assets/989250/6ae43a56-a62d-43ce-9b21-5fe489d94fd8)

**Comment by edublancas** [comment]
the example code is here: https://github.com/ploomber/doc/blob/example/examples/quickstart/notebook.ipynb you can run the notebook end-to-end, then click on the "plot" button that appears at the end

**Comment by bbeat2782** [comment]
To confirm what I understand, is this the expected behavior when plotting histograms?

<img width="442" alt="Screen Shot 2023-06-30 at 8 18 44 PM" src="https://github.com/ploomber/jupysql/assets/43221691/6b194761-4078-4422-bc80-c49a44740e35">

**Comment by edublancas** [comment]
@yafimvo: if you can share your thoughts on why we have this issue, please do. it'll help @bbeat2782

**Comment by yafimvo** [comment]
@edublancas This happens due to 2 reasons
1. Using fill attribute
2. Width of the bar

The fill attribute creates a stacked bar, which means each bar is divided into X segments that represent different subcategories of the overall data. In these cases, it's `island` (3 segments), `species` (3 segments), and `sex` (2 segments).

The width of each bar is dynamic. In these cases, the bars are wide and overlap each other. Since we don't have a border, it looks a bit weird.

I added a border to the bars

<img width="1031" alt="image" src="https://github.com/ploomber/jupysql/assets/103026689/41941fe7-46ae-499b-9b25-ed2186caff81">

I changed the width of the bars
<img width="1034" alt="image" src="https://github.com/ploomber/jupysql/assets/103026689/9d3e0e1c-abe9-4414-ba16-f40192830e13">


There is an option to show 2 histograms on one chart by replacing this:

```
p = (ggplot("plotdata", with_="plotdata", mapping=aes(x=column))
         + geom_histogram(bins=20, fill=fill))
```

with this:

```
p = (ggplot("plotdata", with_="plotdata", mapping=aes(x=[column, fill], fill=["green", "magenta"]))
        + geom_histogram(bins=20))    
```

The problem is that the difference between the X values of these fields is big which makes it difficult to understand the graph

<img width="1046" alt="image" src="https://github.com/ploomber/jupysql/assets/103026689/fd2d0413-054a-4eee-a920-46adfdb2b1b5">

**Comment by edublancas** [comment]
thanks for sharing your feedback  @yafimvo.

@bbeat2782 the best way to validate this is to create the same plots using the same data in [ggplot (in R) ](https://ggplot2.tidyverse.org/), the interface should be pretty similar.

**Comment by bbeat2782** [comment]
> create the same plots using the same data in [ggplot (in R)](https://ggplot2.tidyverse.org/)

Oh, never thought of this way to validate the plots. Thanks.

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Fix code to make sure the vertical breaks in histograms do not show up
2. Change histogram test images
3. Validate the new test images with ggplot (in R)
