### ISSUE TITLE
UI extension - allowing users to see existing table/columns in a connected db

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#76]
This will probably be a widget to allow users view without querying the existing data model in the db, and existing columns.
We probably need more feedback here before building it.

**Comment by edublancas** [comment]
A few thoughts:

The most challenging part here is communicating with the JupyterLab front end. We tried doing something similar in [Ploomber](https://github.com/ploomber/ploomber) a while ago: we wanted to show an alert when a specific event in the Python kernel happened, but we needed help finding an easy solution. It's certainly possible since the visual debugger does [precisely that](https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559), but I bet it'll require some heavy work.

As a first version, we can create an interactive HTML that allows users to explore the tables/columns. Example:

```python
%sqlreport 

# or a Python API?
from SQL import report
report()
```

This could generate an HTML that users can download or interact with directly in the cell. See a list of tables, columns for each table, and maybe even get some summary statistics (note that this overlaps with https://github.com/ploomber/jupysql/issues/66)

Since each DB implements a different API for listing tables/columns, we can leverage [SQLAlchemy](https://stackoverflow.com/questions/6473925/sqlalchemy-getting-a-list-of-tables) to use a single API compatible with many databases.

**Comment by psychemedia** [comment]
Some years ago, I explored various magics for visualising schemas from Postgres database connections; for example: https://github.com/innovationOUtside/ipython_magic_sqlalchemy_schemadisplay which we still use in a course today (the visualisations are a bit ropey, but useful as quick sketches). The dependencies may be quite heavy though...

<img width="554" alt="image" src="https://user-images.githubusercontent.com/82988/217306372-a9e1dac4-59a6-4f65-807f-92d02868279c.png">
