### ISSUE TITLE
New Issue Template that specifies Acceptance Criteria

### ISSUE THREAD

**Issue by nooodle-soup** [ploomber/jupysql#913]
We could make the development process easier to navigate by adding an issue template which has specific sections for defining the issue and clarifying the Acceptance Criteria. It would give a concise idea about the changes to be made, making it easier for the assignee to tackle the issue and provide a sort of checklist for reviewers to reference when reviewing.

Suggested format:

## Issue
--- Issue details here

## Acceptance Criteria (AC)
[ ] Check boxes for each point of the AC 
                 OR
1. Bullets for each point of the AC
---

Acceptance Criteria:
1. A new template file for opening issues
2. Changes in the contribution guidelines

**Comment by edublancas** [comment]
we already have a template: https://github.com/ploomber/jupysql/tree/master/.github/ISSUE_TEMPLATE

We don't put an AC section in the issue template because most of the time, the person opening the issue and the one working on it are not the same. And the purpose of the AC is for the person working on a fix to communicate what they consider as "done", so they can get on the same page with the person opening the issue.
