### ISSUE TITLE
syntax highlighting, formatting and autocompletion doesn't work

### ISSUE THREAD

**Issue by nmetal05** [ploomber/jupysql#930]
### What happens?

syntax highlighting formatting and autocompletion doesn't work which are all features of the jupysql-plugin package

### To Reproduce

I found out the problem is with the version of jupyter-lab ,i was using jupyter-lab 4.0.7 when the issue happened ,then I downgraded to jupyter-lab 3.7 and now those features work.

### OS:

Linux

### JupySQL Version:

0.10.2

### Full Name:

Nizar Sahl

### Affiliation:

I have no affiliation with any company

**Comment by edublancas** [comment]
thanks for your feedback. as you mentioned, the plugin doesn't work with jupyterlab 4. we'll keep this open to track progress

**Comment by fperez** [comment]
Thanks for the excellent work @edublancas!! I was a big fan of the original ipython-sql years ago but had lost track, and rediscovered jupysql now that I'm using it to teach SQL at Berkeley (with a [1,300+ student class, Data 100](https://ds100.org/fa23)!). Many thanks for picking up the torch and adding lots of great new features!

Quick question - do you have a sense of how much work you need to port the extension to JL4, and do you need any input/help from the JLab team? We (speaking with my Jupyter hat on) want to see as many great extensions ported to JL4 so users can have a smooth transition, and if you have questions, folks on the team might be able to help.  I personally would love to be able to use the full feature set of jupysql, including the points above, in our teaching.

If you have specific issues where help could be useful, please let us know, and thanks again for the excellent work!

**Comment by edublancas** [comment]
Hi @fperez, I'm glad you're using JupySQL in your class! Feel free to post any feedback you have.

I ported most of the functionality already (see this [branch](https://github.com/ploomber/jupysql-plugin/tree/jupyter4)). The current challenge is determining the best way to maintain this compatibility with v3 and v4. I spent some time investigating how other projects do this. Sadly, I cannot find the links, but I remember that there was some discussion around having a single codebase that supported both versions, and a second solution was to keep branches (one for v3 and v4).

So, any help would be greatly appreciated! I don't have much experience with JupyterLab frontend extensions so it's unclear what's the best way to move forward.

**Comment by brichet** [comment]
Hey @edublancas, you have a list of some popular extensions [here](https://github.com/jupyterlab/jupyterlab/issues/14590) if you want to take a look.
Some popular extensions seems to use different branches (nbdime, rise, nbgrader...). It probably depends on the required packages and their API changes. 
The following link can be helpful: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#api-breaking-changes

**Comment by brichet** [comment]
@edublancas can you please list the missing functionalities for porting `jupysql` to jupyterlab4.
This would help if some people want to work on it.

Do you have an estimation of the time before a possible release ?

**Comment by edublancas** [comment]
- syntax highlighting
- autocomplete
- sql formatting

the work has been already done here: https://github.com/ploomber/jupysql-plugin/tree/jupyter4

the only missing part is to decide how we'll manage releases, see this [comment](https://github.com/ploomber/jupysql/issues/930#issuecomment-1790925144)

we don't have a timeline yet (we're a pretty small team maintaining a bunch of open-source projects + commercial software), so any help is appreciated! I this is definitely on my radar but since JupySQL's user base has grown significantly in the last few months we keep getting bug reports so it's hard to prioritize.

**Comment by brichet** [comment]
Thanks for the answer.

I think https://github.com/ploomber/jupysql-plugin/tree/jupyter4 is a bit outdated, as mentioned in this [comment](https://github.com/ploomber/jupysql-plugin/pull/63#issuecomment-1825670878). There may be some other PR that should be backported as well.

> * syntax highlighting
> * autocomplete
> * sql formatting

The syntax highlighting and formatting are working well, but the autocomplete is not working on my side.

> the only missing part is to decide how we'll manage releases

What we can often see in extensions (as far as I know):
- 2 branches, each supporting a different version of Jupyterlab, e.g. `3.x` for support to jupyterlab 3 and `main` for the support to jupyterlab 4.
- 2 major versions, each one released from one or the other branch.
- backport PRs that are relevant for both version.

**Comment by edublancas** [comment]
We can keep 0.3.x compatible with JupyterLab 3 and 0.4.x and higher to support JupyterLab 4, then backport PRs to maintain compatibility for both for a few months and stop releasing 0.3.x and only support JupyterLab 4.

We can also add some version checks so if someone is using an incompatible version, we can tell them to upgrade or downgrade.

@brichet: if you have some time, I'd appreciate if you can take the code from https://github.com/ploomber/jupysql-plugin/tree/jupyter4 and open a PR. there's been lots of changes since I worked on it so I think you can just take the code from main and overwrite the logic for the syntax highlighting and formatting

**Comment by brichet** [comment]
@edublancas I opened https://github.com/ploomber/jupysql-plugin/pull/99 to fix the completer

**Comment by edublancas** [comment]
so we just merged https://github.com/ploomber/jupysql-plugin/pull/99 from @brichet which fixes autocomplete in JupyterLab 4! 🎉  with such change all three major features: syntax highlighting, autocomplete and SQL format work on Lab 4 (code is in [`jupyterlab4`](https://github.com/ploomber/jupysql-plugin/tree/jupyter4) branch)

I created a new branch from `main` and named it [`jupyterlab3`](https://github.com/ploomber/jupysql-plugin/tree/jupyterlab3); this branch will contain the version compatible with JupyterLab3, and we'll make `0.3.x` releases from it.

Now, we're ready to merge the code from `jupyter4` into `main`. Since `main` has changed a lot since I created the `jupyter4` branch, I expect a lot of merge conflicts, to ease the transition, we can create a new branch from `main`, cherry-pick changes from `jupyter4` and apply them on top of it.

@brichet let me know if you have time to work on this! feel free to ask questions if anything is unclear.

**Comment by brichet** [comment]
> I created a new branch from `main` and named it [`jupyterlab3`](https://github.com/ploomber/jupysql-plugin/tree/jupyterlab3); this branch will contain the version compatible with JupyterLab3, and we'll make `0.3.x` releases from it.
> 
> Now, we're ready to merge the code from `jupyter4` into `main`.

Nice.

> @brichet let me know if you have time to work on this! feel free to ask questions if anything is unclear.

I can take a look, and I'll ping you if I'm lost in conflicts.

**Comment by brichet** [comment]
@edublancas I think we should also consider removing the dependency to bootstrap.
It brings several bare rules, which change the appearance of jupyterlab.

- **With bootstrap rules**:
![image](https://github.com/ploomber/jupysql/assets/32258950/de22a6d5-3f20-4053-b5ab-9cdcce287b4c)

- **After removing *_reboot.scss* from bootstrap**
![image](https://github.com/ploomber/jupysql/assets/32258950/2a11865c-3584-4dfa-b449-23922042a65d)

It changes at least the size of input, the background color, the status bar... and probably more.

Bootstrap is loaded in https://github.com/ploomber/jupysql-plugin/blob/main/src/widgets/table.ts, but I don't really know what this module is for...

**Comment by edublancas** [comment]
@brichet, thanks for your feedback, I've opened

https://github.com/ploomber/jupysql-plugin/issues/101 
and
https://github.com/ploomber/jupysql-plugin/issues/102

**Comment by edublancas** [comment]
this has been fixed by @brichet in https://github.com/ploomber/jupysql-plugin/commit/a59de9c0b68e4c00e8f4291f98309dc465e16ade (jupysql-plugin 0.4.0). since jupysql-plugin is a dependency in jupysql, installing the latter should now install an extension compatible with JupyterLab 4 🎉
