### ISSUE TITLE
fix cli duplicated arg validation edge case

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#944]
see:  https://github.com/ploomber/jupysql/pull/908#issuecomment-1816197125

**Comment by nooodle-soup** [comment]
Hey @edublancas 
The issue with `-D` and `-d` is that they are both different versions of delete.
`-d` is the alias for `--delete` and `-D` is the alias for `--delete-force`.
They both have different functionality.

Should we still disable duplication for `-D` and `-d`? 
If we don't want these two to work together, `--delete-force` and `--delete` should not work together either, right?

I'll get to implementing the solution for this but do let me know what you think!

**Comment by nooodle-soup** [comment]
Acceptance criteria:

Disable the use of any combination of `-d`, `--delete`, `-D`, `--delete-force` for the `%sqlcmd snippets` magic.

**Comment by edublancas** [comment]
@neelasha23 any thoughts?

**Comment by neelasha23** [comment]
Did you mean we should allow users to use -d / -D/ -A combinations and not raise duplicated argument error? @nooodle-soup 

I think this might lead to inconsistencies. What if user tries to delete some snippets and dependent snippets at the same time. Not impossible but we would have to think of all the cases and then test out before implementing.

@edublancas

**Comment by edublancas** [comment]
@neelasha23 I'm a bit confused about your original comment https://github.com/ploomber/jupysql/pull/908#issuecomment-1816197125

why is this an edge case? based on what @nooodle-soup mentioned, `-d` and `-D` are different arguments so it seems like having them in the same call is ok and shouldn't be counted as duplicates? can you explain why this is an edge case?

**Comment by nooodle-soup** [comment]
@edublancas I did a few tests and as @neelasha23 mentioned in the #908 comment, the current parser allows for only one of the `-d`, `-D`, `-A` and their corresponding double hyphen options to be used at a time. The last option is the only one executed and the others are ignored.

```
%sql --save my_penguins1 SELECT * FROM penguins.csv`
```
```
%sql --save my_penguins2 SELECT * FROM penguins.csv`
```
```
%sql --save my_penguins3 SELECT * FROM penguins.csv`
```
The following command
```
%sqlcmd snippets -d my_penguins1 -D my_penguins2
```
will only remove `my_penguins1` from the stored snippets. This is because the precedence for running the arguments is in the following order because of how the parser for the snippets command is implemented [here](https://github.com/ploomber/jupysql/blob/master/src/sql/cmd/snippets.py#L81-L116).

### Precedence: 
(left -> right :: high -> low) 
`-d` -> `-D` -> `-A`

A minor modification to the code would fix this and allow the use of `-d`, `-D` and `-A` commands together.

**Comment by neelasha23** [comment]
Yes, like @nooodle-soup pointed out when I tested both -d and -D together only one worked the other didn't so it might confuse the user. Either we can disallow using the same duplication logic or we can allow using both, but in that case all the combinations should be properly tested so that no inconsistenct arrisesd when a combination of snippet and dependent snippets are deleted simulatneously.
@edublancas

**Comment by edublancas** [comment]
> Yes, like @nooodle-soup pointed out when I tested both -d and -D together only one worked the other didn't so it might confuse the user. 

I'm not following. does this mean that if I pass -d and -D to %sql only -d or -D work? what was the behavior before introducing the argument logic to detect duplicated arguments, both would work?

**Comment by neelasha23** [comment]
> I'm not following. does this mean that if I pass -d and -D to %sql only -d or -D work? what was the behavior before introducing the argument logic to detect duplicated arguments, both would work?

The default logic was either one would work if both -d and -D are passed (before introducing duplicated argument logic). because argument parser will pick up the latter one. 
@edublancas

**Comment by nooodle-soup** [comment]
@edublancas @neelasha23 The behavior without the argument duplication checks for `delete`, then for `delete-force` and `delete-force-all` in that order. Regardless of how the input is, if `-d` is present, it will take precedence over the rest.
Assuming `my_penguins1`, `my_penguins2` and `my_penguins3` both of the following will only delete the `-d` snippet argument.
1.
```
%sqlcmd snippets -D my_penguins1 -d my_penguins2
```
2.
```
%sqlcmd snippets -A my_penguins3 -d my_penguins2
```

**Comment by neelasha23** [comment]
So either we can allow any combination of `-d` / `-D` and `-A` to work. Or we need to raise the duplicate error message. Which approach should be taken ? @edublancas

**Comment by nooodle-soup** [comment]
@neelasha23 @edublancas I think if we allow using them together, the underlying logic will only execute the arguments based on precedence which is not documented, and the users might completely miss this point if they just skim through the documentation even if it is documented.

We should either change the logic to accommodate the use of any combination of all three options together or prevent usage completely.

**Comment by edublancas** [comment]
I think this discussion is taking too long for an edge case that only a handful of users might encounter. based on the problem, it's unclear what the best solution is. I'll close this for now, we can tackle this if users open issues about this
